env:
  host: "comet"

rpcClient:
  dial: 1
  timeout: 1
  bind: ":3001"

rpcServer:
  dial: 1
  timeout: 1
  bind: ":4000"

tcp:
  bind:
    - ":3101"
  sndbuf: 4096
  rcvbuf: 4096
  keepalive: false
  reader: 32
  readBuf: 1024
  readBufSize: 8192
  writer: 32
  writeBuf: 1024
  writeBufSize: 8129

websocket:
  bind:
    - ":3102"
  tlsOpen: false
  tlsBind:
    - ":3103"
  certFile: "cert.pem"
  privateFile: "private.pem"

protocol:
  timer: 32
  timerSize: 2048
  svrProto: 10
  cliProto: 5
  handshakeTimeout: 5

bucket:
  size: 32
  channel: 1024
  room: 1024
  routineAmount: 32
  routineSize: 1024

