env:
  deployEnv: debug

httpServer:
  network: "tcp"
  addr: ":3000"
  readTimeout: 1
  writeTimeout: 1

rpcServer:
  network: "tcp"
  addr: ":3001"
  timeout: 1

redis:
  network: "tcp"
  addr: ":6379"
  auth: ""
  idleTimeout: 120
  dialTimeout: 1
  readTimeout: 1
  writeTimeout: 1
  poolSize: 1024
  expire: 1800

node:
  heartbeat: 240
  heartbeatMax: 2
  tcpPort: 3101
  wsPort: 3102
  wssPort: 3103

